services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

  database:
    ports:
      - target: 3306
        published: ${MYSQL_PORT:-3306}

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - "27017"
###< doctrine/mongodb-odm-bundle ###
