doctrine_mongodb:
    connections:
        default:
            server: '%env(MONGODB_URL)%'
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: false
            mappings:
                AppDocuments:
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: AppDocuments
